name: 1v1Skywars
author: Marvin2k0
version: 1.0
main: de.marvin2k0.skywars.Skywars
commands:
  setgamespawn:
    permission: 1v1sky.setspawn
  setgamelobby:
    permission: 1v1sky.setlobby
  setylevel:
    permission: 1v1sky.ylevel
  leave:
    permission: 1v1sky.leave